services:
  db:
    image: postgres:16.4
    container_name: match_making_db_dev
    environment:
      POSTGRES_DB: match_making
      POSTGRES_USER: match_making_user
      POSTGRES_PASSWORD: match_making_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
